namespace AP2.DataverseAzureAI.Metadata;

public class BusinessUnit
{
    public object address1_postofficebox { get; set; }
    public string _parentbusinessunitid_value { get; set; }
    public Guid BusinessUnitId { get; set; }
    public object costcenter { get; set; }
    public object fileasname { get; set; }
    public string address1_addressid { get; set; }
    public object address1_upszone { get; set; }
    public object picture { get; set; }
    public string _createdby_value { get; set; }
    public string Name { get; set; }
    public string _organizationid_value { get; set; }
    public int? address1_shippingmethodcode { get; set; }
    public object divisionname { get; set; }
    public object address2_upszone { get; set; }
    public object creditlimit { get; set; }
    public string _modifiedby_value { get; set; }
    public object stockexchange { get; set; }
    public int? address1_addresstypecode { get; set; }
    public object address2_city { get; set; }
    public object address2_longitude { get; set; }
    public object address1_line2 { get; set; }
    public int? address2_addresstypecode { get; set; }
    public bool isdisabled { get; set; }
    public object address2_utcoffset { get; set; }
    public object _modifiedonbehalfby_value { get; set; }
    public object address1_name { get; set; }
    public int? address2_shippingmethodcode { get; set; }
    public object description { get; set; }
    public object address2_stateorprovince { get; set; }
    public object importsequencenumber { get; set; }
    public object address2_line3 { get; set; }
    public DateTime ModifiedOn { get; set; }
    public object _calendarid_value { get; set; }
    public object address1_telephone3 { get; set; }
    public object address1_stateorprovince { get; set; }
    public object address1_telephone2 { get; set; }
    public object address1_telephone1 { get; set; }
    public object tickersymbol { get; set; }
    public object address2_latitude { get; set; }
    public object address1_county { get; set; }
    public object address1_city { get; set; }
    public object address2_postofficebox { get; set; }
    public object address1_fax { get; set; }
    public object _createdonbehalfby_value { get; set; }
    public object address2_line1 { get; set; }
    public object emailaddress { get; set; }
    public bool? workflowsuspended { get; set; }
    public object address1_utcoffset { get; set; }
    public object address1_line3 { get; set; }
    public object address1_postalcode { get; set; }
    public object address1_country { get; set; }
    public object address2_county { get; set; }
    public object address2_postalcode { get; set; }
    public object exchangerate { get; set; }
    public object address1_line1 { get; set; }
    public object address2_country { get; set; }
    public object websiteurl { get; set; }
    public int inheritancemask { get; set; }
    public object address2_name { get; set; }
    public object overriddencreatedon { get; set; }
    public object ftpsiteurl { get; set; }
    public object address2_fax { get; set; }
    public string _transactioncurrencyid_value { get; set; }
    public string address2_addressid { get; set; }
    public object address2_telephone3 { get; set; }
    public object address2_telephone2 { get; set; }
    public object address2_telephone1 { get; set; }
    public object utcoffset { get; set; }
    public object address1_latitude { get; set; }
    public object address1_longitude { get; set; }
    public DateTime createdon { get; set; }
    public object address2_line2 { get; set; }
    public int versionnumber { get; set; }
    public object disabledreason { get; set; }
}
