# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: DataverseAzureAI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: src/AP2.sln
      GITHUB_TOKEN: ${{ github.TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore workloads
      run: dotnet workload restore $env:Solution_Name

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build --no-restore $env:Solution_Name -c ${{ matrix.configuration }} -f net8.0-windows10.0.19041.0

    - name: Publish for Windows
      run: dotnet publish $env:Solution_Name -c ${{ matrix.configuration }} -f net8.0-windows10.0.19041.0

    - name: Upload DataverseAzureAI Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: DataverseAzureAI
        path: src/DataverseAzureAI/bin/${{ matrix.configuration }}/net8.0-windows10.0.19041.0/publish
        if-no-files-found: error

    - name: Upload ConsoleTestApp Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: ConsoleTestApp
        path: src/ConsoleTestApp/bin/${{ matrix.configuration }}/net8.0-windows10.0.19041.0/publish
        if-no-files-found: error

    - name: Upload ap2 Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: ConsoleTestApp
        path: src/ap2/bin/${{ matrix.configuration }}/net8.0-windows10.0.19041.0/win10-x64/publish
        if-no-files-found: error